-- MySQL Script generated by MySQL Workbench
-- Sun May  6 21:46:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SistemaAlmacenamiento
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SistemaAlmacenamiento` ;

-- -----------------------------------------------------
-- Schema SistemaAlmacenamiento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaAlmacenamiento` DEFAULT CHARACTER SET utf8 ;
USE `SistemaAlmacenamiento` ;

-- -----------------------------------------------------
-- Table `SistemaAlmacenamiento`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaAlmacenamiento`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(400) NULL,
  `correo` VARCHAR(500) NULL,
  `cuenta` VARCHAR(500) NULL,
  `contrasena` VARCHAR(500) NULL,
  `fechaRegistro` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaAlmacenamiento`.`Rols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaAlmacenamiento`.`Rols` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(400) NULL,
  `tipo` VARCHAR(400) NULL,
  `descripcion` VARCHAR(400) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaAlmacenamiento`.`Restricciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaAlmacenamiento`.`Restricciones` (
  `Rols_id` INT NOT NULL,
  `Usuarios_id` INT NOT NULL,
  PRIMARY KEY (`Rols_id`, `Usuarios_id`),
  INDEX `fk_Restricciones_Rols1_idx` (`Rols_id` ASC),
  INDEX `fk_Restricciones_Usuarios1_idx` (`Usuarios_id` ASC),
  CONSTRAINT `fk_Restricciones_Rols1`
    FOREIGN KEY (`Rols_id`)
    REFERENCES `SistemaAlmacenamiento`.`Rols` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Restricciones_Usuarios1`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `SistemaAlmacenamiento`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaAlmacenamiento`.`Archivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaAlmacenamiento`.`Archivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(500) NULL,
  `extension` VARCHAR(100) NULL,
  `ruta` VARCHAR(300) NULL,
  `fechaSubida` DATETIME NULL,
  `ultimaModificacion` DATETIME NULL,
  `nombre` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaAlmacenamiento`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaAlmacenamiento`.`Permisos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(400) NULL,
  `nivel` INT NULL,
  `Usuarios_id` INT NOT NULL,
  `Archivos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Usuarios_id`, `Archivos_id`),
  INDEX `fk_Permisos_Usuarios1_idx` (`Usuarios_id` ASC),
  INDEX `fk_Permisos_Archivos1_idx` (`Archivos_id` ASC),
  CONSTRAINT `fk_Permisos_Usuarios1`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `SistemaAlmacenamiento`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Permisos_Archivos1`
    FOREIGN KEY (`Archivos_id`)
    REFERENCES `SistemaAlmacenamiento`.`Archivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaAlmacenamiento`.`Sesions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaAlmacenamiento`.`Sesions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `Usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Usuarios_id`),
  INDEX `fk_Sesions_Usuarios1_idx` (`Usuarios_id` ASC),
  CONSTRAINT `fk_Sesions_Usuarios1`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `SistemaAlmacenamiento`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
